# CORS
cors.allowed.origins=http://localhost:4200

# Datasource
spring.datasource.url=jdbc:sqlite:database.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# AWS S3
aws.s3.bucket-name=ms-api-bucket

# Logs Hibernate (silenciar)
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.org.hibernate.engine.transaction.internal=OFF

# Logs Spring mais limpos (opcional)
logging.level.org.springframework=WARN