# CORS
cors.allowed.origins=http://localhost:4200

# Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/msdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.maximumPoolSize=5
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=none
spring.jackson.default-property-inclusion=non_null

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# AWS S3
aws.s3.bucket-name=ms-api-bucket

# Logs Hibernate
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.org.hibernate.engine.transaction.internal=OFF

# Logs Spring mais limpos
logging.level.org.springframework=WARN